spring.application.name=doorcam
# 1. The Database Coordinates
spring.datasource.url=jdbc:h2:mem:doorcamdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=password

# 2. The Hibernate Blueprint Strategy
spring.jpa.hibernate.ddl-auto=update

# 3. The Visual Web Console
spring.h2.console.enabled=true